monolog:
    handlers:
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        graylog:
            level: info
            type: gelf
            publisher:
                hostname: '%env(GRAYLOG_HOST)%'
                port: '%env(GRAYLOG_PORT)%'
        ignore_failures:
            type: whatfailuregroup
            members: [ graylog ]
