parameters:
    locale: 'fr'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $mailgunDomain: '%env(MAILGUN_DOMAIN)%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Logger\MailgunDateProcessor:
        autoconfigure: false
        tags:
            - { name: monolog.processor, channel: mailgun }
